console.log("Задание 6");
let dolar = prompt("к-тво доларов", "");
dolar = dolar * 0.82;
console.log(dolar, "евро");
console.log("Задание 7");
const gb = prompt("Объем флешки Гб", "");
const mb = 0.82;
let file = ~~(gb / mb);
console.log(file, "файла");
console.log("Задание 8");
const sum = prompt("Сумма денег в лапате", "");
const price = prompt("Цена за шоколадку", "");
let quantity = ~~(sum / price);
let bagOfChocolates = quantity * price;
const surrender = sum - bagOfChocolates;
console.log(quantity, "шт.", surrender, "сдача");
console.log("Задание 9");
let threedigit = prompt("Ведите трехзначное число", "");
let lastDigit = threedigit % 10;
threedigit = ~~(threedigit / 10);
lastDigit = lastDigit * 100;
let threedigit11 = lastDigit + threedigit;
let twoDigit = threedigit11 % 10;
twoDigit = twoDigit * 10;
let threedigit12 = lastDigit + twoDigit;
let triDigit = ~~(threedigit / 10);
threedigit = lastDigit + twoDigit + triDigit;
console.log(threedigit);
console.log("Задание 10");
let contribution = +prompt("Сумма вклада", "");
let percentagePerMonth = (5 / 12) * 2;
contribution = (contribution * percentagePerMonth) / 100;
console.log(contribution);
